name: Main branch

on:
  push:
    paths:
      - "**.go"
      - "**.py"
      - "go.mod"
      - "go.sum"
      - "**.graphql"
      - ".github/workflows/**"
      - "**.sh"
      - "Makefile"
      - "deploy/**"
      - "hub-js/**"
      - "Dockerfile"
      - "!**.md"
      - "**.yaml.tmpl"
    branches:
      - "main"
      - "release-*"

jobs:


  release-cli:
    name: Release the latest Capact CLIs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup environment
        run: |
          . ./hack/ci/setup-env.sh
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up GoReleaser
        run: go install github.com/goreleaser/goreleaser@v0.173.2
      - name: Release latest CLI
        run: |
          make release-latest-binaries
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.APP }}-${{github.sha}}
          path: ./bin
          retention-days: 1
